--- 
- name: Create Route 53
  hosts: localhost
  tasks:
  - name: "Create zone, record and state"
    community.aws.route53:
      state: present
      zone: drscrumptious.com
      record: drscrumptious.drscrumptious.com
      type: A
      value: drscrumptious.drscrumptious.com