--- 
- name: Create Route 53
  hosts: localhost
  tasks:
  - name: "Create zone, record and state"
    community.aws.route53:
      state: present
      zone: drscrumptious.com
      record: http://drscrumptious.com.s3-website.us-east-2.amazonaws.com
      type: A
      value: http://drscrumptious.com.s3-website.us-east-2.amazonaws.com
      alias: True
      alias_hosted_zone_id: Z2O1EMRO9K5GLX
      wait: yes